### PR TITLE
add the view command to show a toot and all of its parents

### PR DESCRIPTION
**Pull request by cerisara**

### CODE REVIEW

**Comment by brrzap** [comment]
aside from the command name, does this do anything #53 doesn't?

**Comment by cerisara** [comment]
Ups.. I've proposed 2 successive pull requests, which may be too much, sorry :-)

For the first one, about the view command, I agree, I had not seen the other pull requests, which apparently is doing the same thing. So yes, I should remove mine I guess...

For the second one, about the lang command, it gives the option to specify one or several languages
and only the toots of these languages will be shown on the public timeline.

**Comment by brrzap** [comment]
if i'm reading it correctly, the `lang` and `details` commands aren't dependent on the `view` command (nor on each other), right? can you split these into separate PRs?

**Comment by cerisara** [comment]
Yes, I could, but:
- lang is highly conflicting with #53 
- view is redundant with #53 
- details should not be there, it's just a debugging stuff.

So overall, I think I should just delete my PR if you don't mind, and wait for #53 to be merged...

**Comment by brrzap** [comment]
ultimately it's your call, but i think if your `lang` change is a good idea and a feature people want, you should go ahead and post it as a separate PR.  put it into its own feature branch on your fork, instead of your fork's master, and do the PR from there; we can review/comment/fixup as needed.

**Comment by cerisara** [comment]
OK, I'm going to do that.
Thanks

**Pull request closed without merging**
