### PR TITLE
Add the packaging metadata to build the tootstream snap

### PR DESCRIPTION
**Pull request by elopio**
This package will let you publish tootstream in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress.

### CODE REVIEW

**Comment by elopio** [comment]
Hello!

You can find more information about snapcraft here: http://snapcraft.io/

To test it in an Ubuntu 16.04 machine:

$ sudo apt install git snapcraft
$ git clone https://github.com/elopio/tootstream
$ cd tootstream
$ git checkout snapcraft
$ snapcraft
$ sudo snap install *.snap --dangerous

(dangerous because the snap you build doesn't come signed from the store. Once you push it to the store, your users will just have to run: `$ sudo snap install tootstream`)

If you would like to publish this in the store, you can easily get continuous builds and delivery from https://build.snapcraft.io/ with a few clicks.

Any questions or comments, please let me know.

**Comment by magicalraccoon** [comment]
I haven't looked at Snapcraft before, but this seems like a great way to distribute.

**Comment by elopio** [comment]
I agree ^_^

**Comment by craigmaloney** [comment]
I want to wait on applying this until we get the Python package set up. it might change a little on how things are executed.

**Comment by craigmaloney** [comment]
@elopio We've made some packaging changes for Tootstream. Please update the .yml file accordingly and submit a new pull request. Once that is submitted we'll pull in for the 0.2.0 release.

Thanks!

**Comment by craigmaloney** [comment]
Closing this request for now as we haven't heard back from you. Please re-submit an updated version of this and we'll be happy to include it in the next release.

Thanks!

**Comment by elopio** [comment]
Sorry for the late reply @craigmaloney. While I was distracted and missed your message, one of our google code-in students packaged and released tootstream: https://github.com/m4sk1n/tootstream

If you would like to adopt it upstream, we can transfer the name. And you can add collaborators to the store, so @m4sk1n can still help maintaining the package.

**Comment by craigmaloney** [comment]
Hi @elopio,

I don't currently have a way to test this so if there's a way to somehow create a pull request to add it in our repo (and maintain it) then that's cool. Otherwise I'd have to accept this on faith.

**Comment by elopio** [comment]
As part of the checklist that you will see here https://github.com/m4sk1n/tootstream#remaining-tasks, @m4sk1n should create a call for testing to get more people to confirm that it works and propose the transfer upstream.

**Comment by magicalraccoon** [comment]
I can fire up a virtual machine later and poke at it later tonight.

**Pull request closed without merging**
