### PR TITLE
Brrzap add toot opts

### PR DESCRIPTION
**Pull request by craigmaloney**
This is an update for @brrzap 's pull request.

### CODE REVIEW

**Comment by magicalraccoon** [comment]
Getting an error when I try to make a public post. Input and output:

```[@raccoon (default)]: toot -v "visibility setting test for tootstream"
Press Ctrl-C to abort and return to the main prompt.
Set visibility [(p)ublic/(u)nlisted/(pr)ivate/(d)irect/None]: p
> /home/raccoon/Projects/tootstream/src/tootstream/toot.py(639)toot()
-> resp = mastodon.status_post(text, **kwargs)
(Pdb)
```
Not sure if this is because of something on my end or not.

**Comment by craigmaloney** [comment]
Nuts. I must've left debugging in the version you have. Let me check to see if this is still there.

**Comment by craigmaloney** [comment]
Yeah, I left debugging in there. I've removed it.

**Comment by magicalraccoon** [comment]
👍

**Comment by craigmaloney** [comment]
Merging. Thank you!

**Pull request merged**
