### PR TITLE
Displaying links. Should make this configurable

### PR DESCRIPTION
**Pull request by craigmaloney**
This is a fist attempt for #159. I'd like to make this configurable rather than a default.

### CODE REVIEW

**Comment by nightpool** [comment]
Maybe instead of making it configurable, you can just de-duplicate with links that are already in the body, so you never see a media attachment link twice even on old statuses? Or, if you think it's too noisy for normal use, have the "media: 4" thing expand when you press enter over it?

**Comment by craigmaloney** [comment]
Not sure what you mean by "expand when you press enter over it"? The way I'm reading that is using something like curses to derive terminal state and I'm not sure that's a road I'd like to go down. :)

**Comment by nightpool** [comment]
sorry, wasn't sure exactly if tootstream was curses based or not already.

**Comment by craigmaloney** [comment]
@nightpool No worries. :grin:

**Comment by craigmaloney** [comment]
This is defaulting to "on" at the moment since Mastodon isn't displaying the links anymore. Closing this out for now.

**Pull request closed without merging**
