### PR TITLE
Adding emoji to shortcode

### PR DESCRIPTION
**Pull request by craigmaloney**
Adds the framework for converting emoji to shortcodes (#156 )

### CODE REVIEW

**Comment by technomancy** [comment]
Thanks for this! It's working with mixed results for me. When viewing https://social.wxcafe.net/@amphetamine/99259627633402189 I see each of the three emoji rendered differently:

```
📿
:pray_hmn_h1:
❤
```

The first character is a tofu square, the second is shortcoded as expected, and the third renders as `HEAVY BLACK HEART` or 0x2764, which predates emoji by several decades. But in the browser it renders as a red . it's hard to tell which is "correct", but turning that into non-emoji unicode is good enough for me. It would be nice to fix the first one somehow though.

**Comment by technomancy** [comment]
Also it would be super if it applied to usernames and not just contents of posts.

**Comment by craigmaloney** [comment]
Hmm, if I copy that over directly and run demojize on it then it converts all of those to the following:

':prayer_beads:\n:pray_hmn_h1:\n:red_heart:\n'

Wonder if there's an encoding issue causing an issue.

**Comment by craigmaloney** [comment]
I tried this and wasn't able to replicate:

@craigmaloney :prayer_beads:  :folded_hands: :red_heart: :hourglass:

Seemed to work for me.

**Comment by craigmaloney** [comment]
Added username demojization.

**Comment by craigmaloney** [comment]
This has been merged into develop. Thanks!

**Pull request merged**
