### PR TITLE
Let users issue commands while streaming

### PR DESCRIPTION
**Pull request by ciex**

### CODE REVIEW

**Comment by craigmaloney** [comment]
This is really cool.

One thing that I noticed while playing with this is that when I brought up an editor it still streamed in the background. Would it be possible to pause the streaming handler until the editor is finished?

Thanks for this!

**Comment by ciex** [comment]
Yes, that is possible, however it makes the code a lot more complex so I would suggest to do that when the code is segmented into more separate modules and maybe even a test suite exists.

So in order to do that I would refactor the `TootListener` class with a publisher subscriber pattern, so that new messages from the stream are enlisted in a queue. A worker would then continuously print messages from the queue to the terminal unless it is in "halted" state.

Two options for enabling halted state:

1. Use curses to detect keypresses even before enter is pressed. Once keys are pressed, enable halted state. Disable halted state a) when backspace has been hit the number of times that keys were pressed or b) when enter has been pressed and the command was submitted.

2. Let user enable halted state by pressing enter. Then show the command prompt, let user enter commands and disable halted state either by submitting a command or with a dedicated command (e.g. `abort`)

Once halted state is exited, the worker will print all messages that have been queued while it was active.

So you see this is quite a bit more complex than the current setup :D Maybe there is another way to do it that I don't see. Do you have other change requests about the PR?

**Comment by craigmaloney** [comment]
I'd rather avoid curses if we can. That tends to lead to heavier code.

One thought that I had would be to pause when the editor is engaged. That way the new toots won't overwrite the editor while it's running. That would be the cheap / cheerful way to work around this.

**Comment by ciex** [comment]
Well, as I said, the two options I see for halting state are quite complex in comparison to this change. Do you want me to close this PR?

**Comment by craigmaloney** [comment]
Nah, let's leave it open for now. We may come up with some better options and I want to build off of this work as much as we can.

**Comment by craigmaloney** [comment]
I must've pulled this in while adding the pull requests for 0.3.4, because it's in there.

I added a flag for checking if we're streaming so it won't bring up the editor. Also added some prompt fixes after displaying toots so the prompt should be consistent while streaming.

I'm going to close out this pull request since it seems to be merged. 

Thanks!

**Pull request closed without merging**
