### PR TITLE
Fixing help so help shows optional arguments better.

### PR DESCRIPTION
**Pull request by craigmaloney**
Use the [<id>] format to show that certain parameters are optional.

### CODE REVIEW

**Comment by magicalraccoon** [comment]
I think at this point it would be a good idea to start separating Help topics into categories. When a user calls Help, they're presented with a big list.

**Comment by craigmaloney** [comment]
I've added sections to the help. Please review and provide feedback on the change. Thanks!

**Comment by magicalraccoon** [comment]
https://github.com/magicalraccoon/tootstream/pull/135/commits/c27edbf497a7b02091773cb7f6551b49a18f5466 Brings a good start, but I'd like to have completely nested help commands-- User typing in `help profile` would then list all the relevant subsections. That would help clean up the text-dump that is our current help output.

**Comment by craigmaloney** [comment]
Added section filtering (it's a little hackish but it works. :) )

**Comment by magicalraccoon** [comment]
This is a little better. Maybe we can also colorize the headings to give it further readability?

**Comment by craigmaloney** [comment]
I thought about that. I'm of two minds on that:

* Colorizing / bolding the headers would improve readability but...
* Making the help screen too loud and distracting could be overloading.

I wanted to keep it simple, especially if someone is having terminal issues.

Thanks for the approval. I'll look into bolding the headers.

**Pull request merged**
