### PR TITLE
upgrade Mastodon.py to 1.0.6, add "local" subcommand

### PR DESCRIPTION
**Pull request by brrzap**
the current version of Mastodon.py (1.0.2) doesn't provide the local timeline but later versions do.  this patch upgrades the dependency to 1.0.6 and adds the `local` command to the REPL.  #55 

this change needs testing to make sure the dependency change doesn't break existing functions.

### CODE REVIEW

**Comment by magicalraccoon** [comment]
Mastodon.py definitely needs to be upgraded, but I worry it would break some commands. Priority issue

**Comment by brrzap** [comment]
yeah, it's a risk.  i've been using v1.0.6 primarily since writing this patch, but could always use more eyes.  in addition to `Mastodon.timeline_local()`, v1.0.6 also provides:

* `.mutes()`, `.account_mute()`, `.account_unmute()`
* `.blocks()`
* `.favourites()`
* `.follow_requests()`, `.follow_request_authorize()`, `.follow_request_reject()`
* `.status_post()` parameters: `sensitive`, `visibility`, `spoiler_text`  (NSFW, public/private/unlisted setting, and CW for toots and replies)

... wow, i should probably diff stuff more often.

**Comment by magicalraccoon** [comment]
Getting an error installing readline, not sure if it's entirely related to this build?

`Searching for readline==6.2.4.1
Reading https://pypi.python.org/simple/readline/
Downloading https://pypi.python.org/packages/f4/01/2cf081af8d880b44939a5f1b446551a7f8d59eae414277fd0c303757ff1b/readline-6.2.4.1.tar.gz#md5=578237939c81fdbc2c8334d168b17907
Best match: readline 6.2.4.1
Processing readline-6.2.4.1.tar.gz
Writing /tmp/easy_install-oapd2axh/readline-6.2.4.1/setup.cfg
Running readline-6.2.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oapd2axh/readline-6.2.4.1/egg-dist-tmp-93hufg_k
Modules/3.x/readline.c:8:20: fatal error: Python.h: No such file or directory
 #include "Python.h"
                    ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
`
removing it from `requirements.txt` seems to help and not break things.

**Comment by brrzap** [comment]
umm.  if you're on debian/ubuntu you might be missing a `-dev` package somewhere.  otherwise no idea.  do you get the same error installing into a fresh virtualenv?

you'll know if readline is operating if you get some history in the repl and ctrl keybinds work (ctrl-L clears screen, ctrl-W erases a word behind the cursor, etc).  i think Click may pull it in without a direct import.

**Comment by magicalraccoon** [comment]
I'm on fedora 25, but I'll load up a few VMs tomorrow and see if it works fresh on other systems.

**Comment by brrzap** [comment]
#54 had installation trouble with similar errors, that's why i was thinking system dependency.  the main readline install needs header files available to compile, hence the `-dev` packages.  probably ought to put a note in the readme about it if we keep readline around.

**Pull request merged**
