### PR TITLE
Apply formatting from black code formatter

### PR DESCRIPTION
**Pull request by JesseWeinstein**
I suggest we use the https://pypi.org/project/black code formatter. Here's a simple PR applying it to the current develop. If we like it, we can request any future PRs also follow it.

### CODE REVIEW

**Comment by craigmaloney** [comment]
I have no objections, but I'm not as familiar with the tool as I should be. Does this change depend on the other changes being merged or is this separate? Thanks!

**Comment by JesseWeinstein** [comment]
This is separate; it's just applying formatting adjustments, and is pretty guaranteed to have no effect on functionality.

**Comment by JesseWeinstein** [comment]
I mainly added it just because I noticed (in making some of my other changes) that I'd ended up with somewhat uneven formatting, and didn't feel like adjusting them manually.

**Comment by craigmaloney** [comment]
I updated this by running `black` manually since there's a conflict. Going to close this pull request. Thanks!

**Pull request closed without merging**
