### PR TITLE
Adding a tootedit command to allow Tootstream to bring up your favorite editor

### PR DESCRIPTION
**Pull request by craigmaloney**
I'd like Tootstream to be able to bring up my favorite editor so I can edit my toots before posting them.

### CODE REVIEW

**Comment by brrzap** [comment]
i'd rather see this done with the existing toot/reply commands somehow (perhaps a flag option similar to #104) rather than requiring a special command for it.

note the click library provides [a `click.edit()` utility](http://click.pocoo.org/6/api/#utilities) which might avoid the need for extra imports.  (it looks like click.edit() does check the `VISUAL` and `EDITOR` environment variables when the `editor` kwarg is not specified.)

**Comment by craigmaloney** [comment]
Hadn't thought to use click.edit() for the editor. Will check it out. Thank you!

Re: the flags vs. stand-alone commands: That would be ideal, but it looks like that functionality is introduced in #104. If that's accepted then I'd like to hang my changes off of that. (eg: ``toot -e`` opens the editor). Is there consensus that this is the approach for adding flags for different behavior?

**Comment by brrzap** [comment]
hrm!  ok, `click.edit()` has a sideeffect i didn't catch, which may be desirable, but may not be. consider a test case like `tootedit foo bar`:

* in 6cc8d10 if the user exits the external editor without changing anything, it returns no input, effectively cancelling the command.  (this may be good! but needs documenting.)
* compare to 17932e0 -- exiting the editor with no changes will still post "foo bar".  

personally i like having a way to cancel.  (and the click.edit() method could still achieve the non-cancel behavior -- if `edited_message` is empty, check `rest` -- if that's what's desired.)

**re: documentation**.  if nowhere else, the help command output (`help tootedit`) should mention the environment variable(s).  if the cancel-on-no-changes behavior is kept, it should be mentioned there as well.  see for example the `stream` and `search` function docstrings.

re: flag consensus.   ¯\_(ツ)_/¯   afaik no decisions have been made; feel free to chime in on #24 or other issues if you want.

**Comment by craigmaloney** [comment]
Thank you. I added documentation for the tootedit command. Should the flags be added I'll update / make a new pull request to merge them in so it's not a separate command.

**Comment by craigmaloney** [comment]
Bah, I left a stray pdb in here. Going to forge a new pull request.

**Pull request closed without merging**
