### PR TITLE
Adding humanize to show how many minutes ago an event occurred.

### PR DESCRIPTION
**Pull request by craigmaloney**
Adding humanize to show the difference in time from current time.

### CODE REVIEW

**Comment by magicalraccoon** [comment]
This seems to work well! What are your thoughts about putting the humanized text before the time output?

**Comment by craigmaloney** [comment]
I prefer it afterward simply because my eye is drawn to it more.

**Comment by magicalraccoon** [comment]
That's fair, approved.

**Comment by craigmaloney** [comment]
Awesome. Thank you!

**Pull request merged**
