### PR TITLE
Made public and home feeds print in real-time

### PR DESCRIPTION
**Pull request by claiire**
To exit from the feed hit C-c. This should bring you back to the command prompt. Note that the refresh rate of the feeds are controlled by a global variable REFRESH_RATE, declared at the top of the toot.py file. 

This addresses issue #12.

### CODE REVIEW

**Comment by magicalraccoon** [comment]
This prevents commands while the feed is running, right? Wouldn't that make faving/boosting impossible without relaunching?

**Comment by claiire** [comment]
Yeah, it would not be possible to use commands with this setup. I'm fairly certain we'd have to move to a curses based UI if we want the sort of control over the terminal we'd need to be able to update the feed in realtime and accept commands.

**Comment by magicalraccoon** [comment]
Multithreading is an option?

**Comment by claiire** [comment]
I don't know enough about multithreading to be able to say to be honest. 

The way I'm seeing it is that right now the program is just printing to stdout until it's told to ask for input. Aside from the curses library I'm not sure how one would get an interactable command line and a stream of text updating in realtime at the same time. 

I think you might be more knowledgeable about how to solve this problem than I am.

**Comment by magicalraccoon** [comment]
It's worth taking a look at Rainbowstream-- A huge inspiration for this project.

**Pull request closed without merging**
