### PR TITLE
add output icons

### PR DESCRIPTION
**Pull request by gonzote**
this patch adds a global lookup dict of unicode glyphs.  uses added in this patch:

* toot visibility,
* toot/following/follower counts on user account info,
* lock icon on usernames when an account is locked

### CODE REVIEW

**Comment by magicalraccoon** [comment]
I'm getting an error after running `home`:

`Traceback (most recent call last):
  File "toot.py", line 492, in <module>
    main()
  File "/home/raccoon/Projects/tootstream/tootstream/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/raccoon/Projects/tootstream/tootstream/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/raccoon/Projects/tootstream/tootstream/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/raccoon/Projects/tootstream/tootstream/lib/python3.5/site-packages/click-6.6-py3.5.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "toot.py", line 488, in main
    cmd_func(mastodon, rest)
  File "toot.py", line 233, in home
    (GLYPHS['locked']+" " if toot['account']['locked'] else "") ))
KeyError: 'locked'
`

Have you had any issues with this?

**Comment by magicalraccoon** [comment]
This is a great way to visualize toot information. I think I would like it better going like `♺:0 ♥:0 id:7    vis:🌎`. Seems to read a little better that way?

**Comment by brrzap** [comment]
sorry about the 'locked' crash, my testing account isn't following enough chatty locked accounts.  i  have no strong preference as to the order of these, or even the particular glyphs used.  just throwing ideas out there.

**Comment by magicalraccoon** [comment]
Looks great, thanks for the catch. Merging.

**Pull request merged**
