### PR TITLE
Update Dismiss command to use Note IDs

### PR DESCRIPTION
**Pull request by craigmaloney**
Update the dismiss command to use the notification IDs:

* Added note ID to notifications
* Updated dismiss command to use note ID
* Updated help to reflect the new usage

### CODE REVIEW

**Comment by craigmaloney** [comment]
waiting on an updated release of Mastodon.py as the dismiss command doesn't work with the 1.1.1 release.

**Comment by magicalraccoon** [comment]
Shall we close for now?

**Comment by craigmaloney** [comment]
I'd rather merge it first. :grin:

**Comment by craigmaloney** [comment]
Merged per tootstream discussion on gitter.

**Pull request merged**
